// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TireInventory.Data;

#nullable disable

namespace TireInventory.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TireInventory.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("LocationId")
                        .HasColumnType("bigint");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TireInventory.Models.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("ChangedColumns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KeyValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TireInventory.Models.AuditTrail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Changes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PerformedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PerformedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("TireInventory.Models.CompanyInfo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbbiBusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbbi_Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbbi_Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbbi_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbbi_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbbi_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbbi_Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("tbbi_Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("tbbi_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbbi_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbbi_ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Bo_BusinessInformation");
                });

            modelBuilder.Entity("TireInventory.Models.DailyExpense", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ExpenseHeadId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LocationDetailsId")
                        .HasColumnType("bigint")
                        .HasColumnName("LocationId");

                    b.Property<string>("PayType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tblDailyExpense");
                });

            modelBuilder.Entity("TireInventory.Models.Departments", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tbid_DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tbid_IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_BO_ItemDepartment");
                });

            modelBuilder.Entity("TireInventory.Models.Distributors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tbdl_DistributoAdd");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tbdl_DistributorName");

                    b.Property<DateTime?>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_DistributorList");
                });

            modelBuilder.Entity("TireInventory.Models.ExpenseHead", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbeh_HeadName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_ExpenseHead");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("tbid_Bolt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbid_Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbid_DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tbid_DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("tbid_DistributorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbid_HoleS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tbid_InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("tbid_ItemCategory")
                        .HasColumnType("bigint");

                    b.Property<long?>("tbid_ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("tbid_LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tbid_Qty")
                        .HasColumnType("int");

                    b.Property<string>("tbid_Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbid_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbid_TaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("tbid_Taxable")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbid_UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbid_Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tbid_InvoiceId");

                    b.HasIndex("tbid_ItemId");

                    b.ToTable("tbl_Invoice_Details");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbim_AdjAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbim_AdjTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbim_CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Delinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbim_DisAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbim_DisPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbim_EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_IDNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tbim_InvDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("tbim_InvoiceIdRad")
                        .HasColumnType("bigint");

                    b.Property<bool>("tbim_Item_Delete_after_Invoice_Create")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbim_Labour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("tbim_LaywayDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("tbim_LaywayNo")
                        .HasColumnType("bigint");

                    b.Property<bool>("tbim_Left_Front")
                        .HasColumnType("bit");

                    b.Property<bool>("tbim_Left_Rear")
                        .HasColumnType("bit");

                    b.Property<string>("tbim_License")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("tbim_LocationDetailsId")
                        .HasColumnType("bigint")
                        .HasColumnName("tbim_LocationId");

                    b.Property<string>("tbim_Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Odometer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbim_PaidAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbim_PayInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_RefundType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tbim_Right_Front")
                        .HasColumnType("bit");

                    b.Property<bool>("tbim_Right_Rear")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbim_SaleTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbim_SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("tbim_TaxId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("tbim_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbim_TreadDepth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_VehicleMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tbim_LocationDetailsId");

                    b.HasIndex("tbim_TaxId");

                    b.ToTable("tbl_Invoice_Master");
                });

            modelBuilder.Entity("TireInventory.Models.InvoicePayments", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("tbip_Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("tbip_InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("tbip_LayawayDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("tbip_LayawayId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("tbip_PayAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("tbip_PaymentId")
                        .HasColumnType("bigint");

                    b.Property<string>("tbip_PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tdip_fromlayaway")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tbip_InvoiceId");

                    b.HasIndex("tbip_PaymentId");

                    b.ToTable("tbl_Invoice_Payment", null, t =>
                        {
                            t.HasTrigger("tg_Invoice_Payment_Insert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceRefundDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("tbird_Bolt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbird_Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbird_DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tbird_DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("tbird_DistributorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbird_HoleS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tbird_InvoiceRefundId")
                        .HasColumnType("bigint");

                    b.Property<int?>("tbird_ItemCategory")
                        .HasColumnType("int");

                    b.Property<long?>("tbird_ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("tbird_LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tbird_Qty")
                        .HasColumnType("int");

                    b.Property<string>("tbird_Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbird_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbird_TaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("tbird_Taxable")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbird_UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbird_Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tbird_InvoiceRefundId");

                    b.HasIndex("tbird_ItemId");

                    b.ToTable("tbl_Invoice_Refund_Details");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceRefundMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbirm_AdjAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbirm_Delinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbirm_DisAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbirm_DisPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("tbirm_InvRefundDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("tbirm_InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("tbirm_InvoiceRefundIdRad")
                        .HasColumnType("bigint");

                    b.Property<bool>("tbirm_Item_Delete_after_Invoice_Refund_Create")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbirm_Labour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbirm_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbirm_RefundAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbirm_RefundType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbirm_SaleTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbirm_SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbirm_Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("tbirm_InvoiceId");

                    b.ToTable("tbl_Invoice_Refund_Master");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceRefundPayments", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("tbirp_Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("tbirp_InvoiceRefundId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("tbirp_RefundAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("tbirp_RefundMethodId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("tbirp_InvoiceRefundId");

                    b.HasIndex("tbirp_RefundMethodId");

                    b.ToTable("tbl_Invoice_Refund_Payment");
                });

            modelBuilder.Entity("TireInventory.Models.ItemMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Bolt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbim_Code")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbim_CodeTOT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("tbim_DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("tbim_HoleS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tbim_ItemCategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("tbim_ItemCategory");

                    b.Property<long>("tbim_LocationId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("tbim_OURP")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tbim_Qty")
                        .HasColumnType("int");

                    b.Property<int?>("tbim_QtyOp")
                        .HasColumnType("int");

                    b.Property<string>("tbim_Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("tbim_ThrashDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("tbim_Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tbim_DistributorId");

                    b.HasIndex("tbim_ItemCategoryId");

                    b.HasIndex("tbim_LocationId");

                    b.ToTable("tbl_ItemMaster", null, t =>
                        {
                            t.HasTrigger("tg_ItemMaster_Insert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TireInventory.Models.LayawayDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("tbid_Bolt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbid_Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbid_DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tbid_DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("tbid_DistributorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbid_HoleS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tbid_InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("tbid_ItemCategory")
                        .HasColumnType("bigint");

                    b.Property<long?>("tbid_ItemId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("tbid_LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tbid_Qty")
                        .HasColumnType("int");

                    b.Property<string>("tbid_Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbid_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbid_TaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("tbid_Taxable")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbid_UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbid_Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tbid_InvoiceId");

                    b.HasIndex("tbid_ItemId");

                    b.ToTable("tbl_Layaway_Details");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbim_AdjAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbim_AdjTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbim_CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Delinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbim_DisAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbim_DisPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbim_EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_IDNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("tbim_InvDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("tbim_InvoiceIdRad")
                        .HasColumnType("bigint");

                    b.Property<bool>("tbim_Item_Delete_after_Layaway_Create")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbim_Labour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("tbim_Left_Front")
                        .HasColumnType("bit");

                    b.Property<bool>("tbim_Left_Rear")
                        .HasColumnType("bit");

                    b.Property<string>("tbim_License")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("tbim_LocationId")
                        .HasColumnType("bigint");

                    b.Property<string>("tbim_Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Odometer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbim_PaidAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbim_PayInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_RefundType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tbim_Right_Front")
                        .HasColumnType("bit");

                    b.Property<bool>("tbim_Right_Rear")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbim_SaleTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbim_SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("tbim_TaxId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("tbim_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbim_TreadDepth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_VehicleMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbim_Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tbim_LocationId");

                    b.HasIndex("tbim_TaxId");

                    b.ToTable("tbl_Layaway_Master");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayPayments", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("tbip_Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("tbip_InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("tbip_PayAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("tbip_PaymentId")
                        .HasColumnType("bigint");

                    b.Property<string>("tbip_PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tbip_InvoiceId");

                    b.HasIndex("tbip_PaymentId");

                    b.ToTable("tbl_Layaway_Payment", null, t =>
                        {
                            t.HasTrigger("tg_tbl_Layaway_Payment_Insert");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("TireInventory.Models.LayawayRefundDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("tbird_Bolt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbird_Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbird_DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tbird_DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("tbird_DistributorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbird_HoleS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tbird_ItemCategory")
                        .HasColumnType("int");

                    b.Property<long?>("tbird_ItemId")
                        .HasColumnType("bigint");

                    b.Property<int>("tbird_Layaway_Qty")
                        .HasColumnType("int");

                    b.Property<decimal?>("tbird_Layaway_Qty_LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("tbird_Layaway_Qty_TaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("tbird_Layaway_RefundId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("tbird_LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("tbird_Qty")
                        .HasColumnType("int");

                    b.Property<string>("tbird_Series")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbird_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbird_TaxAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("tbird_TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("tbird_Taxable")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbird_UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbird_Zone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("tbird_ItemId");

                    b.HasIndex("tbird_Layaway_RefundId");

                    b.ToTable("tbl_Layaway_Refund_Details");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayRefundMaster", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Layaway_tbim_AdjAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Layaway_tbim_AdjTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Layaway_tbim_CompanyAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_Delinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Layaway_tbim_DisAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Layaway_tbim_DisPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Layaway_tbim_EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_IDNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Layaway_tbim_InvDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("Layaway_tbim_InvoiceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Layaway_tbim_InvoiceIdRad")
                        .HasColumnType("bigint");

                    b.Property<bool>("Layaway_tbim_Item_Delete_after_Layaway_Create")
                        .HasColumnType("bit");

                    b.Property<decimal>("Layaway_tbim_Labour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Layaway_tbim_Left_Front")
                        .HasColumnType("bit");

                    b.Property<bool>("Layaway_tbim_Left_Rear")
                        .HasColumnType("bit");

                    b.Property<string>("Layaway_tbim_License")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_Odometer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Layaway_tbim_PaidAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Layaway_tbim_PayInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Layaway_tbim_Right_Front")
                        .HasColumnType("bit");

                    b.Property<bool>("Layaway_tbim_Right_Rear")
                        .HasColumnType("bit");

                    b.Property<decimal>("Layaway_tbim_SaleTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Layaway_tbim_SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long?>("Layaway_tbim_TaxId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Layaway_tbim_Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Layaway_tbim_TreadDepth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_VehicleMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Layaway_tbim_Year")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbirm_AdjAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbirm_Delinfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbirm_DisAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbirm_DisPer")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("tbirm_Item_Delete_after_Layaway_Refund_Create")
                        .HasColumnType("bit");

                    b.Property<decimal>("tbirm_Labour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("tbirm_LayawayRefundDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("tbirm_LayawayRefundIdRad")
                        .HasColumnType("bigint");

                    b.Property<string>("tbirm_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbirm_RefundAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("tbirm_RefundType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbirm_SaleTax")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbirm_SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("tbirm_Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Layaway_tbim_InvoiceId");

                    b.HasIndex("Layaway_tbim_TaxId");

                    b.ToTable("tbl_Layaway_Refund_Master");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayRefundPayments", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("tbirp_Date")
                        .HasColumnType("datetime2");

                    b.Property<long>("tbirp_Layaway_RefundId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("tbirp_RefundAmt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("tbirp_RefundMethodId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("tbirp_Layaway_RefundId");

                    b.HasIndex("tbirp_RefundMethodId");

                    b.ToTable("tbl_Layaway_Refund_Payment");
                });

            modelBuilder.Entity("TireInventory.Models.LocationDetails", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyInfoId")
                        .HasColumnType("bigint")
                        .HasColumnName("tbld_BusinessId");

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbld_Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbld_Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbld_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbld_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbld_Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbld_LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbld_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbld_State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbld_ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyInfoId");

                    b.ToTable("tbl_BO_LocationDetails");
                });

            modelBuilder.Entity("TireInventory.Models.PaymentNames", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tbpn_IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("tbpn_PaymentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_PaymentName");
                });

            modelBuilder.Entity("TireInventory.Models.RefundMethodNames", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("tbrmn_IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("tbrmn_RefundMethodName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_RefundMethodName");
                });

            modelBuilder.Entity("TireInventory.Models.TaxId", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbti_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbti_ComName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbti_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbti_TaxNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_TaxId");
                });

            modelBuilder.Entity("TireInventory.Models.TaxRateModified", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("SetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tbtm_Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("tbtm_TaxRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("tbl_TaxRateModified");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TireInventory.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TireInventory.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TireInventory.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceDetails", b =>
                {
                    b.HasOne("TireInventory.Models.InvoiceMaster", "tbid_Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("tbid_InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.ItemMaster", "tbid_Item")
                        .WithMany()
                        .HasForeignKey("tbid_ItemId");

                    b.Navigation("tbid_Invoice");

                    b.Navigation("tbid_Item");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceMaster", b =>
                {
                    b.HasOne("TireInventory.Models.LocationDetails", "tbim_LocationDetails")
                        .WithMany()
                        .HasForeignKey("tbim_LocationDetailsId");

                    b.HasOne("TireInventory.Models.TaxId", "tbim_Tax")
                        .WithMany()
                        .HasForeignKey("tbim_TaxId");

                    b.Navigation("tbim_LocationDetails");

                    b.Navigation("tbim_Tax");
                });

            modelBuilder.Entity("TireInventory.Models.InvoicePayments", b =>
                {
                    b.HasOne("TireInventory.Models.InvoiceMaster", "tbip_Invoice")
                        .WithMany("InvoicePayments")
                        .HasForeignKey("tbip_InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.PaymentNames", "tbip_Payment")
                        .WithMany()
                        .HasForeignKey("tbip_PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbip_Invoice");

                    b.Navigation("tbip_Payment");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceRefundDetails", b =>
                {
                    b.HasOne("TireInventory.Models.InvoiceRefundMaster", "tbird_InvoiceRefund")
                        .WithMany("InvoiceRefundDetails")
                        .HasForeignKey("tbird_InvoiceRefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.ItemMaster", "tbird_Item")
                        .WithMany()
                        .HasForeignKey("tbird_ItemId");

                    b.Navigation("tbird_InvoiceRefund");

                    b.Navigation("tbird_Item");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceRefundMaster", b =>
                {
                    b.HasOne("TireInventory.Models.InvoiceMaster", "tbirm_Invoice")
                        .WithMany("InvoiceRefundMasters")
                        .HasForeignKey("tbirm_InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbirm_Invoice");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceRefundPayments", b =>
                {
                    b.HasOne("TireInventory.Models.InvoiceRefundMaster", "tbirp_InvoiceRefund")
                        .WithMany("InvoiceRefundPayments")
                        .HasForeignKey("tbirp_InvoiceRefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.RefundMethodNames", "tbirp_RefundMethod")
                        .WithMany()
                        .HasForeignKey("tbirp_RefundMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbirp_InvoiceRefund");

                    b.Navigation("tbirp_RefundMethod");
                });

            modelBuilder.Entity("TireInventory.Models.ItemMaster", b =>
                {
                    b.HasOne("TireInventory.Models.Distributors", "tbim_Distributor")
                        .WithMany()
                        .HasForeignKey("tbim_DistributorId");

                    b.HasOne("TireInventory.Models.Departments", "tbim_ItemCategory")
                        .WithMany()
                        .HasForeignKey("tbim_ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.LocationDetails", "tbim_Location")
                        .WithMany()
                        .HasForeignKey("tbim_LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbim_Distributor");

                    b.Navigation("tbim_ItemCategory");

                    b.Navigation("tbim_Location");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayDetails", b =>
                {
                    b.HasOne("TireInventory.Models.LayawayMaster", "tbid_Invoice")
                        .WithMany("LayawayDetails")
                        .HasForeignKey("tbid_InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.ItemMaster", "tbid_Item")
                        .WithMany()
                        .HasForeignKey("tbid_ItemId");

                    b.Navigation("tbid_Invoice");

                    b.Navigation("tbid_Item");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayMaster", b =>
                {
                    b.HasOne("TireInventory.Models.LocationDetails", "tbim_Location")
                        .WithMany()
                        .HasForeignKey("tbim_LocationId");

                    b.HasOne("TireInventory.Models.TaxId", "tbim_Tax")
                        .WithMany()
                        .HasForeignKey("tbim_TaxId");

                    b.Navigation("tbim_Location");

                    b.Navigation("tbim_Tax");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayPayments", b =>
                {
                    b.HasOne("TireInventory.Models.LayawayMaster", "tbip_Invoice")
                        .WithMany("LayawayPayments")
                        .HasForeignKey("tbip_InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.PaymentNames", "tbip_Payment")
                        .WithMany()
                        .HasForeignKey("tbip_PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbip_Invoice");

                    b.Navigation("tbip_Payment");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayRefundDetails", b =>
                {
                    b.HasOne("TireInventory.Models.ItemMaster", "tbird_Item")
                        .WithMany()
                        .HasForeignKey("tbird_ItemId");

                    b.HasOne("TireInventory.Models.LayawayRefundMaster", "tbird_Layaway_Refund")
                        .WithMany("LayawayRefundDetails")
                        .HasForeignKey("tbird_Layaway_RefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbird_Item");

                    b.Navigation("tbird_Layaway_Refund");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayRefundMaster", b =>
                {
                    b.HasOne("TireInventory.Models.LayawayMaster", "Layaway_tbim_Invoice")
                        .WithMany("LayawayRefundMasters")
                        .HasForeignKey("Layaway_tbim_InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.TaxId", "Layaway_tbim_Tax")
                        .WithMany()
                        .HasForeignKey("Layaway_tbim_TaxId");

                    b.Navigation("Layaway_tbim_Invoice");

                    b.Navigation("Layaway_tbim_Tax");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayRefundPayments", b =>
                {
                    b.HasOne("TireInventory.Models.LayawayRefundMaster", "tbirp_Layaway_Refund")
                        .WithMany("LayawayRefundPayments")
                        .HasForeignKey("tbirp_Layaway_RefundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TireInventory.Models.RefundMethodNames", "tbirp_RefundMethod")
                        .WithMany()
                        .HasForeignKey("tbirp_RefundMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tbirp_Layaway_Refund");

                    b.Navigation("tbirp_RefundMethod");
                });

            modelBuilder.Entity("TireInventory.Models.LocationDetails", b =>
                {
                    b.HasOne("TireInventory.Models.CompanyInfo", "CompanyInfo")
                        .WithMany()
                        .HasForeignKey("CompanyInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompanyInfo");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceMaster", b =>
                {
                    b.Navigation("InvoiceDetails");

                    b.Navigation("InvoicePayments");

                    b.Navigation("InvoiceRefundMasters");
                });

            modelBuilder.Entity("TireInventory.Models.InvoiceRefundMaster", b =>
                {
                    b.Navigation("InvoiceRefundDetails");

                    b.Navigation("InvoiceRefundPayments");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayMaster", b =>
                {
                    b.Navigation("LayawayDetails");

                    b.Navigation("LayawayPayments");

                    b.Navigation("LayawayRefundMasters");
                });

            modelBuilder.Entity("TireInventory.Models.LayawayRefundMaster", b =>
                {
                    b.Navigation("LayawayRefundDetails");

                    b.Navigation("LayawayRefundPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
